### PR TITLE
Closes #45: App preview addeed

### LINKED ISSUE #45: [GSSoC'23] Improve the project image dashboard in the Readme file
### Is your feature request related to a problem? Please describe.

- The app screenshots look a little plain and basic. We need to make it more presentable. I just want to make it seem more appealing for anyone visiting the project
- Also, we need to have the presentations in one banner and the screenshots need to be from the google playstore build.
- This is an example of what I can do (from my own repo)
flutter_projects_1

### Describe the solution you'd like

- I would put the images(screenshots) from the Taaveez/graphics folder and add a frame to it, and finally add it to a poster. Doing this, will make the readers feel like they are holding the app in their hands
- I would choose the colour of the background in accordance with the design theme

### Describe alternatives you've considered

We can also add a video scrolling screen for the application.

### Additional context

@avinashkranjan Please assign this to me under the GSSoC'23.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by anandanmukh**
- Application preview has been added to the main README file
- a separate folder "assets" has been containing all the information.

## Fixes Issue
Fixes Issue #45 

## Changes proposed
- Application preview has been added to the main README file
- a separate folder "assets" has been containing all the information. The folder contains screenshots (both framed and normal)
- the folder also contains a separate README file that outlines how to change the application preview in the future with all the necessary links and resources
- The link for the canva project has also been added, which can be used to modify the preview further

## Check List (Check all the applicable boxes) 

- [ x] My code follows the code style of this project.
- [ x] All new and existing tests passed.
- [ x] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.

### Screenshot

taaveez
### Actual Preview
preview

## Note to reviewers
- All the required changes are added in the "assets" directory, which can be referred to as well for making any more changes in the future.

### CODE REVIEW

**Review by Vaibhav2002 — APPROVED** [review]

**Comment by Suryansh1720001** [comment]
@anandanmukh 
Please check the updated application by running the code on your local system. Note that the preview pages included here are not the actual ones. Additionally, please ensure that dark and light modes are available.

**Comment by anandanmukh** [comment]
@Suryansh1720001 Ok got it... Also, do you need the poster to have both light and dark mode screenshots in the banner?

**Comment by Suryansh1720001** [comment]
@anandanmukh 
Yes, you can made banner also and use the theme related to the application.

**Comment by anandanmukh** [comment]
I have added the required changes on the application_preview branch. Pleasee go through it, and let me know if there are any further changes required.

**Comment by anandanmukh** [comment]
taaveez_application_preview

**Pull request closed without merging**
