### PR TITLE
Closes #95 and #96

### LINKED ISSUE #95: open source and privacy policy hindi translation
### What happened?

Open source and privacy policy hindi translation not available in app

### Reproduction steps

```bash
Steps to reproduce the behavior:

1. Go to 'setting page'
2. Click on 'string to add to resource file'
3. Scroll down to 'string.xml (hi-rlN) file'
4. add alternative string for open source and privacy policy to string.xml (hi-rlN)
```

### Expected behavior

open source and privacy policy should be available in English and Hindi language

### Screenshots

_No response_

### Version

1.1.0 (Default)

### Version (If not available above)

_No response_

### What devices are you seeing the problem on?

Mobile

### Device Name, Android Version and Screen Size

Android 10

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Deepshikhayadav**
## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots
WhatsApp Image 2023-06-22 at 11 47 25 AM

## Note to reviewers

UI changes has made in this PR

### CODE REVIEW

**Comment by Deepshikhayadav** [comment]
issue #72 has been fixed
close #72

**Comment by Vaibhav2002** [comment]
@Deepshikhayadav this issue was assigned to someone else, so you cant work on it

**Review by Vaibhav2002 — APPROVED** [review]
LGTM!

**Comment by Suryansh1720001** [comment]
@Deepshikhayadav 
Provide me the screen recording for these changes.

**Pull request closed without merging**
