### PR TITLE
Recycler view update

### PR DESCRIPTION
**Pull request by Ivan2001otp**
## Fixes Issue
Fixes and improves the performance of recycler view.
Implementation of clean code and MVVM architecture.

## Changes proposed
Implementation of viewmodel for mvvm, and diffUtil callback to improve the performance of recycler view

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Ivan2001otp** [comment]
Hello sir, can you please provide me the link of joining Android development tech stack - channel in Discord. It will be very helpful for me .Thanks in advance.

**Comment by Suryansh1720001** [comment]
Hello @Ivan2001otp,
There is no dedicated channel specifically focused on the Android development tech stack.

**Comment by Ivan2001otp** [comment]
Hello sir,
Actually DiffUtil callback is a utility class provided by android framework
that improves the performance of recycler view by updating the list item
displayed. When we use "Recycler view" to display a list of items, you
often need to update the contents dynamically.For example  when you add,
remove ,or update the items in the list , we want recycler view to reflect
these changes without recreating the entire list from scratch. This is
where DiffUtil comes into play.DiffUtil performs a computation to determine
the differences between two lists, typically old list and new list. It
calculates the minimum set of updates needed to transform the old list into
the new list.
Thus , I implemented this in the project - Taaveez.

**Comment by Suryansh1720001** [comment]
@Ivan2001otp 
Okay, I will merge it, but there is a problem.
The current code includes the MVVM architecture and additional animation UI, which is causing an issue. Could you kindly remove those parts or create a new pull request by forking the code again, creating a separate branch, and making changes specifically for upgrading the RecyclerView component?

**Comment by Suryansh1720001** [comment]
Since @Ivan2001otp has been unresponsive and the task has been assigned to another person, I am proceeding to close it now.

**Pull request closed without merging**
