### PR TITLE
Fixed language inconsistency when content language is set to Hindi

### PR DESCRIPTION
**Pull request by ManogjnaSinguluri**
## Fixes Issue

Fixes issue #100 

## Changes proposed

The pop-up question, notes heading, and certain options in the settings page were not properly reflecting the content language when set to Hindi are are correctly adjusted to match the selected content language.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Screenshot_2023-07-04-17-18-31-63_abdf78ab9f542e323f858763712c8230    Screenshot_2023-07-04-17-18-43-04_abdf78ab9f542e323f858763712c8230

### CODE REVIEW

**Review by Vaibhav2002 — APPROVED** [review]
LGTM!
@ManogjnaSinguluri Please confirm that now each and everything is in Hindi when language is set to Hindi

**Comment by ManogjnaSinguluri** [comment]
Yes, except the "Connect with us", "Current version" headings in about page. As they are standard ones ,did not changed them. If you want them changed, please let me know

**Comment by Vaibhav2002** [comment]
> Yes, except the "Connect with us", "Current version" headings in about page. As they are standard ones ,did not changed them. If you want them changed, please let me know

You can change the 'Connect with us' text, let "Current Version" be as it is

**Comment by ManogjnaSinguluri** [comment]
Done! changed the 'Connect with us' text too. Everything is in Hindi if when the language is set to Hindi. Please let me know if any changes need to be done

**Review by Vaibhav2002 — APPROVED** [review]
LGTM! Great Work.

**Comment by ManogjnaSinguluri** [comment]
The pull request Please let me know of any changes need to be done

**Pull request closed without merging**
