### PR TITLE
NullPointerException in AddContent method at line 146 #72

### PR DESCRIPTION
**Pull request by arqam365**

### CODE REVIEW

**Comment by Vaibhav2002** [comment]
@arqam365 please create an issue first, also attach a recording of the crash

**Review by Vaibhav2002 — APPROVED** [review]
LGTM!
Fixes #72

**Comment by Suryansh1720001** [comment]
Hello @arqam365 
Please update the functionality in the "Update Content" or "Edit Content" feature. After making the changes, provide a screen recording to demonstrate the updated functionality.

**Comment by Suryansh1720001** [comment]
already done in app

**Pull request closed without merging**
